"""Runbook and help contracts for the Python TUI migration."""

from __future__ import annotations

from .catalog import (
    HELP_ALIASES,
    HELP_TOPICS,
    discover_runbooks,
    get_help_topic,
    list_help_topics,
    load_runbook,
    parse_runbook_metadata,
    validate_runbook,
)
from .models import (
    HelpTopic,
    RequirementCheck,
    RequirementResult,
    RequirementStatus,
    RunbookAction,
    RunbookExecutionScope,
    RunbookCommandResult,
    RunbookConfirmationRequired,
    RunbookMetadata,
    RunbookParameter,
    RunbookPreview,
    RunbookRisk,
    RunbookValidationReport,
    RunbookSource,
    check_requirements,
    command_preview,
    preview_runbook,
    run_contract,
    run_runbook,
    script_preview,
    source_for_path,
    source_rank,
)

__all__ = [
    "HELP_ALIASES",
    "HELP_TOPICS",
    "HelpTopic",
    "RequirementCheck",
    "RequirementResult",
    "RequirementStatus",
    "RunbookAction",
    "RunbookCommandResult",
    "RunbookConfirmationRequired",
    "RunbookExecutionScope",
    "RunbookMetadata",
    "RunbookParameter",
    "RunbookPreview",
    "RunbookRisk",
    "RunbookValidationReport",
    "RunbookSource",
    "check_requirements",
    "command_preview",
    "discover_runbooks",
    "get_help_topic",
    "list_help_topics",
    "load_runbook",
    "parse_runbook_metadata",
    "preview_runbook",
    "run_contract",
    "run_runbook",
    "script_preview",
    "source_for_path",
    "source_rank",
    "validate_runbook",
]
